---

- name: Check if MSC is installed
  ansible.builtin.command: "which managedsoftwareupdate"
  register: result
  failed_when: result.rc != 0
  changed_when: False

- name: Extract list of installed apps
  ansible.builtin.command: plutil -extract "processed_installs" json "/Library/Managed Installs/InstallInfo.plist" -o -
  register: installed_list
  changed_when: False

- name: Filter lists
  ansible.builtin.set_fact:
    filtered_msc_installs: "{{ msc_installs | difference(installed_list.stdout) }}"
    filtered_msc_uninstalls: "{{ msc_uninstalls | intersect(installed_list.stdout) }}"

- name: Count actions
  ansible.builtin.set_fact:
    msc_actions_count: "{{ (filtered_msc_installs|length + filtered_msc_uninstalls|length) }}"

- include_tasks: processor.yml
  when: "msc_actions_count|int > 0"
